version: 2
jobs:
  build:
    working_directory: ~/JavaScriptApiAutomation
    docker:
      - image: circleci/node:8.0
      - image: mongo:3.4.4
    steps:
      - run:
          name: "Checking NodeJs + NPM Version"
          command: |
            node --version
            npm --version
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run: npm install
      
      - run:
          name: Run API Tests
          command: 'npm test'

